spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/h2-db/hong-tabulator
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

logging.level:
  org.hibernate.SQL: debug


hong:
  img:
    path: 'D:\hongFileDir\hongTabulatorFile\'
  ckImg:
    pattern: '/ckImage/**'
    path: 'D:/hongFileDir/hongTabulatorFile/ckImage/'