server:
  port: 9094

spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    generate-ddl: true
    database: default
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML
    cache: false
